### ISSUE TITLE
Cannot touch button

### ISSUE THREAD

**Issue by Yfuruchin** [sozialhelden/wheelmap-iphone2#5]
we cannnot touch the save/ edit button in information screen.
Could you check the situation?

OS：iOS 9.1
APP ver: v3.0 buid 130
lang: Japanese

best  regards

![image](https://cloud.githubusercontent.com/assets/4961152/11414055/1d711ebc-9434-11e5-84f3-ab3628918f38.png)

**Comment by holgerd** [comment]
@Yfuruchin sorry for not replying earlier. We have a newer version since then. Does this problem still occur for you?

**Comment by Yfuruchin** [comment]
@holgerd Thank you for replying, there is no problem
 we checked on  iOS App v3.0.2(Build 201) ; )

**Comment by holgerd** [comment]
great!

**Comment by lennerd** [comment]
![](http://mrwgifs.com/wp-content/uploads/2013/11/Cant-Touch-This-MC-Hammer-Dance-Gif.gif)
